const ROW_SIZE = 29;
const COLUMN_SIZE = 65;
const KNIGHT_ROW = 20;
const KNIGHT_COL = 20;
const PRINCESS_ROW = 25;
const PRINCESS_COL = 50;

export {
  ROW_SIZE,
  COLUMN_SIZE,
  KNIGHT_ROW,
  KNIGHT_COL,
  PRINCESS_ROW,
  PRINCESS_COL,
};
